name: Auto Merge

on:
  workflow_dispatch:
  pull_request:
    branches: [ main ]

jobs:
  auto-merge:
    if: ${{ github.head_ref == 'chore/update-nix-fetch-git' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@1af3b93b6815bc44a9784bd300feb67ff0d1eeb3 # v6.0.0

      - uses: actions/create-github-app-token@67018539274d69449ef7c02e8e71183d1719ab42 # v2.1.4
        id: generate-token
        with:
          app-id: ${{ secrets.CPR_APP_ID }}
          private-key: ${{ secrets.CPR_APP_PRIVATE_KEY }}

      - name: Enable Pull Request Automerge
        run: gh pr merge --squash --auto ${{ github.event.number }}
        env:
          GH_TOKEN: ${{ steps.generate-token.outputs.token }}
